language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty
  - sudo apt-get update -qq

install: 
  # C++14
  # - sudo apt-get install -qq g++-5
  # - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev libqt53d5 
  - sudo apt-get install -qq qtbase5-dev qt5-default qttools5-dev-tools
  # - sudo apt-get install libqt53dcore5 libqt53dextras5 libqt53drender5 libqt53dinput5
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
    #Qt variables
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - source /opt/qt593/bin/qt593-env.sh
  - cd src
  - /opt/qt593/bin/qmake -project
  - /opt/qt593/bin/qmake
  - make
#- ./snake
